export const initialFounders = [
    "Oisin Hanrahan (Handy)",
    "Umang Dua (Handy)",
    "Adi Tatarko (Houzz)",
    "Alon Cohen (Houzz)",
    "Joshua Reeves (Gusto)",
    "Edward Kim (Gusto)",
    "Tomer London (Gusto)",
    "Henry Ward (Carta)",
    "Jack Conte (Patreon)",
    "Sam Yam (Patreon)",
    "Emily Weiss (Glossier)",
    "Dylan Field (Figma)",
    "Ivan Zhao (Notion)",
    "Simon Last (Notion)",
    "Chris Britt (Chime)",
    "Ryan King (Chime)",
    "Zach Perret (Plaid)",
    "William Hockey (Plaid)",
    "Apoorva Mehta (Instacart)",
    "Max Mullen (Instacart)",
    "Brandon Leonardo (Instacart)",
    "Ryan Petersen (Flexport)",
    "Simón Borrero (Rappi)",
    "Sebastian Mejia (Rappi)",
    "Felipe Villamarin (Rappi)",
    "Chris Comparato (Toast)",
    "Aman Narang (Toast)",
    "Steve Fredette (Toast)",
    "Jonathan Grimm (Toast)",
    "Henrique Dubugras (Brex)",
    "Pedro Franceschi (Brex)",
    "Alex Timm (Root)",
    "Dan Manges (Root)",
    "Michael Acton Smith (Calm)",
    "Alex Tew (Calm)",
    "Vishal Garg (Better.com)",
    "Daniel Schreiber (Lemonade)",
    "Shai Wininger (Lemonade)",
    "Harry Hurst (Pipe)",
    "Josh Mangel (Pipe)",
    "Zain Allarakhia (Pipe)",
    "Andrey Khusid (Miro)",
    "Brian Long (Attentive)",
    "Andrew Jones (Attentive)",
    "Ian Crosby (Bench)",
    "Jordan Menashy (Bench)",
    "Pavel Rodionov (Bench)",
    "Adam Saint (Bench)",
    "Ryan Breslow (Bolt)",
    "Payal Kadakia (ClassPass)",
    "Mary Biggins (ClassPass)",
    "Sanjiv Sanghavi (ClassPass)",
    "Daphne Koller (Coursera)",
    "Andrew Ng (Coursera)",
    "Jeff Maggioncalda (Coursera)",
    "Eren Bali (Udemy)",
    "Gagan Biyani (Udemy)",
    "Oktay Caglar (Udemy)",
    "Luis von Ahn (Duolingo)",
    "Severin Hacker (Duolingo)",
    "Andrew Dudum (Hims & Hers)",
    "James Reinhart (ThredUp)",
    "Oliver Lubin (ThredUp)",
    "Chris Homer (ThredUp)",
    "Jennifer Hyman (Rent the Runway)",
    "Jennifer Fleiss (Rent the Runway)",
    "Marco Zappacosta (Thumbtack)",
    "Jonathan Swanson (Thumbtack)",
    "Sander Daniels (Thumbtack)",
    "Ryan Holmes (Hootsuite)",
    "Dario Meli (Hootsuite)",
    "David Tedman (Hootsuite)",
    "Ali Parsa (Babylon Health)",
    "Nima Ghamsari (Blend)",
    "Erin Collard (Blend)",
    "Eugene Marinelli (Blend)",
    "Rosco Hill (Blend)",
    "Seth Sternberg (Honor)",
    "Sandy Jen (Honor)",
    "Cameron Ring (Honor)",
    "Jennifer Fitzgerald (Policygenius)",
    "Francois de Lame (Policygenius)",
    "Joshua Viner (Wag!)",
    "Brandon Schwartz (Wag!)",
    "Jonathan Viner (Wag!)",
    "Alex Chesterman (Cazoo)",
    "Jeff Cavins (Outdoorsy)",
    "Jen Young (Outdoorsy)",
    "Steven Gutentag (Keeps)",
    "Demetri Karagas (Keeps)",
    "Jonathan Neman (Sweetgreen)",
    "Nicolas Jammet (Sweetgreen)",
    "Nathaniel Ru (Sweetgreen)",
    "Jim VandeHei (Axios)",
    "Mike Allen (Axios)",
    "Roy Schwartz (Axios)",
    "Elan Babchuck (BentoBox)",
    "Krystle Mobayeni (Bentobox)",
    "Heather Hasson (Figs)",
    "Trina Spear (Figs)",
    "Wade Foster (Zapier)",
    "Bryan Helmig (Zapier)",
    "Mike Knoop (Zapier)",
    "Adora Cheung (Homejoy)",
    "Aaron Cheung (Homejoy)",
    "Leah Busque (TaskRabbit)",
    "Stacy Brown-Philpot (TaskRabbit, former CEO)",
    "Noah Ready-Campbell (Built Robotics)",
    "Andrew Boggeri (Built Robotics)",
    "Wade Eyerly (Surf Air)",
    "David Eyerly (Surf Air)",
    "Tristan Walker (Walker & Company)",
    "Christina Cacioppo (Vanta)",
    "Jake Schneider (Vanta)",
    "Heidi Zak (ThirdLove)",
    "David Spector (ThirdLove)",
    "Jess Lee (Polyvore)",
    "Pasha Sadri (Polyvore)",
    "Victoria Ransom (Wildfire Interactive)",
    "Alain Chuard (Wildfire Interactive)",
    "Ryan Hoover (Product Hunt)",
    "Jules Pieri (The Grommet)",
    "Joanne Domeniconi (The Grommet)",
    "Dave Gilboa (Warby Parker)",
    "Neil Blumenthal (Warby Parker)",
    "Andrew Hunt (Warby Parker)",
    "Jeffrey Raider (Warby Parker, also Harry’s)",
    "Andy Katz-Mayfield (Harry’s)",
    "Michael Preysman (Everlane)",
    "Jesse Genet (Lumi)",
    "Stephan Ango (Lumi)",
    "Shan-Lyn Ma (Zola)",
    "Nobu Nakaguchi (Zola)",
    "Kevin Ryan (Gilt, Business Insider - known serial entrepreneur)",
    "Dwight Crow (Whisper)",
    "Michael Heyward (Whisper)",
    "Julia Hartz (Eventbrite)",
    "Kevin Hartz (Eventbrite)",
    "Renaud Visage (Eventbrite)",
    "Patrick Brown (Impossible Foods)",
    "Josh Tetrick (Eat Just)",
    "Ilir Sela (Slice)",
    "Carisa Miklusak (tilr)",
    "Matt O'Connor (AdQuick)",
    "Maren Kate Donovan (Zirtual)",
    "Bo Fishback (Zaarly)",
    "Eric Migicovsky (Pebble)",
    "Kathryn Minshew (The Muse)",
    "Alexandra Cavoulacos (The Muse)",
    "Mathilde Collin (Front)",
    "Laurent Perrin (Front)",
    "Keith McCarty (Eaze)",
    "Carol Reiley (Drive.ai)",
    "Sameep Tandon (Drive.ai)",
    "Richard Craib (Numerai)",
    "Andrew Mason (Groupon, former CEO/founder, not widely considered a billionaire)",
    "Ken Lin (Credit Karma, founder & former CEO)",
    "Nichole Mustard (Credit Karma)",
    "Jon Stein (Betterment)",
    "Eli Broverman (Betterment)",
    "Noah Kerner (Acorns)",
    "Jeff Cruttenden (Acorns)",
    "Walter Cruttenden (Acorns)",
    "Sarah Leary (Nextdoor)",
    "Nirav Tolia (Nextdoor)",
    "Prakash Janakiraman (Nextdoor)",
    "David Wiesen (Nextdoor)",
    "T.J. Parker (PillPack)",
    "Elliot Cohen (PillPack)",
    "Manny Medina (Outreach)",
    "Andrew Kinzer (Outreach)",
    "Gordon Hempton (Outreach)",
    "Michael Rosenbaum (Catalyte)",
    "Lindsay Kaplan (Chief)",
    "Carolyn Childers (Chief)",
    "Jessica Ewing (Literati)",
    "Eoghan McCabe (Intercom)",
    "Des Traynor (Intercom)",
    "Ciaran Lee (Intercom)",
    "David Barrett (Expensify)",
    "Shoaib Makani (KeepTruckin, now Motive)",
    "Obaid Khan (KeepTruckin)",
    "Jessica Mah (inDinero)",
    "Andy Su (inDinero)",
    "Justin Kan (Atrium, previously Twitch co-founder—while wealthy, not broadly cited as a billionaire)",
    "Robin Chan (Operator)",
    "Garrett Kimball (Operator)",
    "Sergey Faguet (Wikimart)",
    "Jared Friedman (Scribd)",
    "Trip Adler (Scribd)",
    "Tikhon Bernstam (Scribd, Parse)",
    "Shafqat Islam (NewsCred)",
    "Ira Winker (NewsCred)",
    "Russ Heddleston (DocSend)",
    "Alyssa Ravasio (Hipcamp)",
    "Tim Young (Hipcamp)",
    "Rich Fulop (Brooklinen)",
    "Vicki Fulop (Brooklinen)",
    "Gregg Spiridellis (JibJab)",
    "Evan Spiridellis (JibJab)",
    "Nicolas Dessaigne (Algolia)",
    "Julien Lemoine (Algolia)",
    "Megan O'Connor (Clark)",
    "Carly Strife (BarkBox)",
    "Matt Meeker (BarkBox)",
    "Henrik Werdelin (BarkBox)",
    "Noah Dentzel (Nomad)",
    "Brian Hahn (Nomad)",
    "Timo Rein (Pipedrive)",
    "Urmas Purde (Pipedrive)",
    "Ragnar Sass (Pipedrive)",
    "Martin Henk (Pipedrive)",
    "Daniel Yanisse (Checkr)",
    "Arnaud Weber (Checkr)",
    "Jon Steinberg (Cheddar)",
    "Marcela Sapone (Hello Alfred)",
    "Jessica Beck (Hello Alfred)",
    "Dylan Serota (Lyra Health)",
    "Dena Bravata (Lyra Health)",
    "David Ebersman (Lyra Health)",
    "Rohan Pavuluri (Upsolve)",
    "Jonathan Petts (Upsolve)",
    "Edith Harbaugh (LaunchDarkly)",
    "John Kodumal (LaunchDarkly)",
    "Melanie Gordon (Tapingo)",
    "Daniel Almog (Tapingo)",
    "Udi Geva (Tapingo)",
    "Hayley Barna (Birchbox)",
    "Katia Beauchamp (Birchbox)",
    "Jacob DeGeer (iZettle)",
    "Magnus Nilsson (iZettle)",
    "Deepak Rao (X1 Card)",
    "Siddharth Batra (X1 Card)",
    "Michelle Zatlyn (Cloudflare)",
    "Matthew Prince (Cloudflare)",
    "Lee Holloway (Cloudflare)",
    "Peter Reinhardt (Segment)",
    "Calvin French-Owen (Segment)",
    "Ilya Volodarsky (Segment)",
    "Ian White (ChartHop)",
    "Ellen Chisa (Dark)",
    "Paul Biggar (Dark)",
    "Jeff Wald (WorkMarket)",
    "Jeffrey Leventhal (WorkMarket)",
    "Dan Lewis (Convoy)",
    "Grant Goodale (Convoy)",
    "Alex Turnbull (GrooveHQ)",
    "Chris Clark (GrooveHQ)",
    "Danny Shader (PayNearMe)",
    "Rachel Drori (Daily Harvest)",
    "Kyle Taylor (The Penny Hoarder)",
    "Dan Teran (Managed by Q)",
    "Saman Rahmanian (Ro)",
    "Rob Schutz (Ro)",
    "Karan Mehta (Ro)",
    "Gregg Brockway (Chairish)",
    "Eric Grosse (Chairish)",
    "Dave Ferguson (Nuro)",
    "Jiajun Zhu (Nuro)",
    "Christine Moseley (Full Harvest)",
    "Tammy Sun (Carrot Fertility)",
    "Tessa Price (Carrot Fertility)",
    "Tristan Handy (dbt Labs)",
    "Drew Banin (dbt Labs)",
    "Christine T. Nguyen (Kindbody)",
    "Gina Bartasi (Kindbody)",
    "Eduardo Vivas (Bright)",
    "Nathalie Molina Niño (Brava Investments)",
    "Al Goldstein (Avant)",
    "John Sun (Avant)"
  ];
