import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

export const initialStartups = [
    "ArdorLink – Transitioned from 'NFT aggregator' to 'cross-chain aggregator'.",
    "StartSafe – Transitioned from 'security tool' to 'ZK-based privacy suite'.",
    "NeoSwap – Transitioned from 'simple DEX' to 'multi-chain swap aggregator'.",
    "LumiCore – Transitioned from 'data indexer' to 'modular indexing aggregator'.",
    "VesperBeam – Transitioned from 'payment dApp' to 'multi-chain checkout aggregator'.",
    "TokenFuse – Transitioned from 'DeFi aggregator' to 'NFT-based yield platform'.",
    "CloudRift – Transitioned from 'file storage' to 'edge computing aggregator'.",
    "PixShift – Transitioned from 'image editor' to 'generative NFT studio'.",
    "GuildSpan – Transitioned from 'guild management' to 'DAO aggregator toolkit'.",
    "ByteMelt – Transitioned from 'crowdfunding tool' to 'NFT-based fundraiser'.",
    "ArcSynergy – Transitioned from 'sidechain solution' to 'modular L2 aggregator'.",
    "MintHalo – Transitioned from 'launchpad tool' to 'multi-chain NFT minter'.",
    "DriveNode – Transitioned from 'node hosting' to 'automated infra aggregator'.",
    "FenceLink – Transitioned from 'time-lock vault' to 'escrow aggregator'.",
    "BeamCast – Transitioned from 'video aggregator' to 'token-gated streaming'.",
    "FieldLoop – Transitioned from 'farm management' to 'tokenized yield aggregator'.",
    "ZapFlow – Transitioned from 'token burning app' to 'auto-burn aggregator'.",
    "KaleidoMate – Transitioned from 'NFT gallery' to 'AI-generated collectibles'.",
    "SwapNectar – Transitioned from 'arbitrage aggregator' to 'auto-optimizing DEX router'.",
    "FrameShift – Transitioned from 'NFT frames' to 'creator licensing aggregator'.",
    "TuneSnap – Transitioned from 'music marketplace' to 'on-chain royalty manager'.",
    "BoardSpan – Transitioned from 'governance aggregator' to 'ZK-voting platform'.",
    "CoinLatch – Transitioned from 'micropayment solution' to 'streaming finance engine'.",
    "EventHarbor – Transitioned from 'ticketing dApp' to 'NFT-based event aggregator'.",
    "AquaRise – Transitioned from 'liquidity aggregator' to 'omnichain DEX suite'.",
    "SparkNode – Transitioned from 'DAO tooling' to 'community engagement aggregator'.",
    "HoloScope – Transitioned from 'analytics aggregator' to 'blockchain data indexer'.",
    "MacroFlow – Transitioned from 'stablecoin tool' to 'lending aggregator'.",
    "HorizonSpan – Transitioned from 'bridge aggregator' to 'interoperable rollup router'.",
    "BeatBox – Transitioned from 'token performance tracker' to 'social token analytics'.",
    "BetaFlock – Transitioned from 'staking-as-a-service' to 'liquid staking aggregator'.",
    "NovaFolio – Transitioned from 'portfolio tracker' to 'NFT & DeFi aggregator'.",
    "FluxVault – Transitioned from 'ETH staking' to 'liquid cross-chain staking aggregator'.",
    "NodeHive – Transitioned from 'infra aggregator' to 'multi-chain node marketplace'.",
    "KeyQuill – Transitioned from 'crypto key manager' to 'multichain identity aggregator'.",
    "WispDEX – Transitioned from 'arbitrage aggregator' to 'auto DEX aggregator'.",
    "GraphBeam – Transitioned from 'data indexing' to 'modular subgraph aggregator'.",
    "Lockverse – Transitioned from 'locked staking' to 'on-chain escrow aggregator'.",
    "MeterFlow – Transitioned from 'gas fee aggregator' to 'dynamic gas optimizer'.",
    "PrimeCast – Transitioned from 'MEV aggregator' to 'anti-MEV rollup aggregator'.",
    "ProtoBloom – Transitioned from 'data shard aggregator' to 'modular chain synergy'.",
    "SiloLink – Transitioned from 'yield aggregator' to 'cross-layer yield aggregator'.",
    "VisaLift – Transitioned from 'payments aggregator' to 'web3 subscription platform'.",
    "FlowSolve – Transitioned from 'mobile DeFi tool' to 'L2 bridging aggregator'.",
    "AlphaHive – Transitioned from 'NFT aggregator' to 'fractional NFT marketplace'.",
    "DropTracker – Transitioned from 'token airdrop tool' to 'airdrop analytics aggregator'.",
    "RiskGauge – Transitioned from 'risk aggregator' to 'on-chain scoring engine'.",
    "ExDock – Transitioned from 'exchange aggregator' to 'unified trading front-end'.",
    "OrbitLink – Transitioned from 'L2 aggregator' to 'celestia-based chain aggregator'.",
    "BeamOrb – Transitioned from 'node hosting' to 'cross-chain infra aggregator'.",
    "DreamGrid – Transitioned from 'game asset aggregator' to 'blockchain gaming marketplace'.",
    "CrossPortal – Transitioned from 'bridge aggregator' to 'virtual chain bridging suite'.",
    "VaultCrate – Transitioned from 'NFT vault aggregator' to 'NFT fractionalization platform'.",
    "MintBlitz – Transitioned from 'NFT launch tool' to 'multi-chain mint aggregator'.",
    "SpinStack – Transitioned from 'DEX aggregator' to 'automated trading aggregator'.",
    "RollDock – Transitioned from 'rollup aggregator' to 'L2 chain aggregator'.",
    "MaxBorrow – Transitioned from 'lending aggregator' to 'NFT-based collateral hub'.",
    "StarSpan – Transitioned from 'staking aggregator' to 'cosmos-based extension'.",
    "PixelShift – Transitioned from 'NFT creation tool' to 'AI generative art aggregator'.",
    "CoinFount – Transitioned from 'crypto faucet tool' to 'on-chain reward aggregator'.",
    "LensArch – Transitioned from 'social aggregator' to 'Lens Protocol-based media suite'.",
    "FungiMine – Transitioned from 'fungi NFT aggregator' to 'gamified spore token system'.",
    "MinerBay – Transitioned from 'BTC mining aggregator' to 'tokenized hashpower suite'.",
    "ZoomLoom – Transitioned from 'sidechain aggregator' to 'metaverse extension solution'.",
    "LinkEver – Transitioned from 'chain aggregator' to 'cross-rollup synergy platform'.",
    "DevShift – Transitioned from 'dev aggregator' to 'web3 environment toolkit'.",
    "WarpRoute – Transitioned from 'transaction aggregator' to 'MEV-protected router'.",
    "ArkCover – Transitioned from 'insurance aggregator' to 'tokenized coverage aggregator'.",
    "QuestLoop – Transitioned from 'task aggregator' to 'web3 freelance DAO platform'.",
    "BlockGate – Transitioned from 'producer aggregator' to 'blockspace manager aggregator'.",
    "CubDAO – Transitioned from 'youth aggregator' to 'NFT-based learning hub'.",
    "TorchSwap – Transitioned from 'token burning aggregator' to 'deflationary aggregator'.",
    "TapestryX – Transitioned from 'NFT tapestry aggregator' to 'on-chain generative patterns'.",
    "AntiSandwich – Transitioned from 'frontrunning aggregator' to 'MEV protection tool'.",
    "ParaBridge – Transitioned from 'parachain aggregator' to 'substrate bridging aggregator'.",
    "TideFuse – Transitioned from 'liquidity aggregator' to 'concentrated liquidity manager'.",
    "BlurConnect – Transitioned from 'NFT aggregator' to 'cross-market NFT aggregator'.",
    "NodeSafe – Transitioned from 'location aggregator' to 'trusted geolocation layer'.",
    "FocusDeFi – Transitioned from 'DeFi aggregator' to 'MEV-proof aggregator'.",
    "HedgeSpan – Transitioned from 'hedging aggregator' to 'options/futures aggregator'.",
    "ReflectRoute – Transitioned from 'synthetic aggregator' to 'cross-asset derivative aggregator'.",
    "ForgeLayer – Transitioned from 'layer aggregator' to 'multi-domain bridging chain'.",
    "FrostLine – Transitioned from 'futures aggregator' to 'cross-chain perps aggregator'.",
    "QuietBridge – Transitioned from 'privacy aggregator' to 'zkRollup-based transactions'.",
    "GaugeLink – Transitioned from 'governance aggregator' to 'voting power synergy'.",
    "SeedArk – Transitioned from 'crowdfunding aggregator' to 'equity token launch'.",
    "DeltaBridge – Transitioned from 'price feed aggregator' to 'oracle bridging aggregator'.",
    "PranaDose – Transitioned from 'carbon aggregator' to 'token-based carbon offset'.",
    "LinkSpoke – Transitioned from 'cross-chain aggregator' to 'L2 relayer aggregator'.",
    "DawnVault – Transitioned from 'incubation aggregator' to 'web3 accelerator platform'.",
    "SparkTask – Transitioned from 'batch aggregator' to 'gas-optimized multi-call aggregator'.",
    "AutoArb – Transitioned from 'arbitrage aggregator' to 'auto routing aggregator'.",
    "JetMesh – Transitioned from 'multichain aggregator' to 'gasless bridging aggregator'.",
    "MeldEcho – Transitioned from 'DeFi aggregator' to 'token bridging aggregator'.",
    "LotusLink – Transitioned from 'bridge aggregator' to 'NFT bridging aggregator'.",
    "FloraDex – Transitioned from 'NFT staking aggregator' to 'collectible staking platform'.",
    "GridRise – Transitioned from 'energy aggregator' to 'tokenized renewable energy tool'.",
    "SeedFunder – Transitioned from 'startup token aggregator' to 'token-based VC platform'.",
    "ScriptFlow – Transitioned from 'smart contract aggregator' to 'no-code contract generation'.",
    "ChromaKey – Transitioned from 'color NFT aggregator' to 'fractional pixel ownership'.",
    "ParcelChain – Transitioned from 'logistics aggregator' to 'NFT-based shipping tokens'.",
    "FlowLift – Transitioned from 'IDO aggregator' to 'multi-chain launchpad aggregator'.",
    "ApexForge – Transitioned from 'node aggregator' to 'PoS aggregator manager'.",
    "SenseBlurb – Transitioned from 'narrative aggregator' to 'interactive storytelling NFTs'.",
    "MuralDock – Transitioned from 'digital mural aggregator' to 'AR NFT experiences'.",
    "TapScore – Transitioned from 'scoreboard aggregator' to 'web3 scoreboard platform'.",
    "CoinMind – Transitioned from 'AI aggregator' to 'token intelligence aggregator'.",
    "MintHive – Transitioned from 'NFT aggregator' to 'airdrop aggregator suite'.",
    "VentureWeave – Transitioned from 'funding aggregator' to 'DAO-based investment aggregator'.",
    "VaultNexus – Transitioned from 'liquidity aggregator' to 'cross-protocol vault aggregator'.",
    "Hyperliquid – Transitioned from 'layer 3 solution' to 'layer 1 chain'.",
    "Mantle – Transitioned from 'BitDAO governance project' to 'modular L2 ecosystem'.",
    "Zerion – Transitioned from 'DeFi aggregator' to 'web3 wallet'.",
    "Celestia – Transitioned from 'LazyLedger' to 'modular data availability layer'.",
    "PaperTrail – Transitioned from 'invoice tool' to 'DAO-based finance suite'.",
    "FlowMingle – Transitioned from 'NFT marketplace' to 'social token ecosystem'.",
    "DriveChain – Transitioned from 'web3 data storage' to 'cross-chain data layer'.",
    "SpotLit – Transitioned from 'book reviews aggregator' to 'creator NFT platform'.",
    "AeroLaunch – Transitioned from 'web3 launchpad' to 'asset tokenization hub'.",
    "ChainMingle – Transitioned from 'dating dApp' to 'VR metaverse community'.",
    "BondRiser – Transitioned from 'micro-bond protocol' to 'cross-chain staking aggregator'.",
    "SwapPulse – Transitioned from 'DEX aggregator' to 'multi-chain yield router'.",
    "EpochVerse – Transitioned from 'time-token concept' to 'virtual real estate hub'.",
    "NovaLane – Transitioned from 'DeFi router' to 'interoperable NFT pipeline'.",
    "RevoScope – Transitioned from 'decentralized analytics' to 'blockchain data indexer'.",
    "MacroMint – Transitioned from 'stablecoin aggregator' to 'lending & borrowing protocol'.",
    "HorizonLink – Transitioned from 'bridge aggregator' to 'interoperable rollup solution'.",
    "PulseBox – Transitioned from 'token performance tracker' to 'social token analytics'.",
    "BetaStake – Transitioned from 'staking-as-a-service' to 'liquid staking aggregator'.",
    "EventBloom – Transitioned from 'web3 ticketing' to 'NFT-based event management'.",
    "AquaDeFi – Transitioned from 'cross-chain liquidity aggregator' to 'omnichain DEX suite'.",
    "SparkHive – Transitioned from 'DAO tooling' to 'community engagement platform'.",
    "Metaview – Transitioned from 'virtual art gallery' to 'immersive NFT experiences'.",
    "CloudRift – Transitioned from 'decentralized cloud' to 'edge computing aggregator'.",
    "FuseMint – Transitioned from 'token minting platform' to 'metaverse brand hub'.",
    "TuneFlow – Transitioned from 'music NFT marketplace' to 'royalty streaming service'.",
    "FrameKey – Transitioned from 'NFT frames aggregator' to 'creator licensing hub'.",
    "StoryFolio – Transitioned from 'writing dApp' to 'content tokenization suite'.",
    "GraphLux – Transitioned from 'web3 data graph' to 'cross-chain index aggregator'.",
    "PixKit – Transitioned from 'NFT image editor' to 'on-chain generative art studio'.",
    "CoreBridge – Transitioned from 'layer-2 bridging solution' to 'ZK-powered L1 extension'.",
    "Finnect – Transitioned from 'peer-to-peer lending' to 'DeFi-based microcredit pool'.",
    "LumenAID – Transitioned from 'charity token aggregator' to 'NFT philanthropic platform'.",
    "RoadMap – Transitioned from 'decentralized travel planner' to 'token-incentivized tours'.",
    "SparkLink – Transitioned from 'data oracles aggregator' to 'cross-chain oracle framework'.",
    "GeoFi – Transitioned from 'location-based DeFi' to 'geospatial NFT marketplace'.",
    "BlockChef – Transitioned from 'recipe token aggregator' to 'food-based NFT membership'.",
    "LayerLite – Transitioned from 'L2 sidechain' to 'sovereign rollup framework'.",
    "MintMatrix – Transitioned from 'token tracking tool' to 'NFT portfolio manager'.",
    "TradeBloom – Transitioned from 'CEX aggregator' to 'semi-decentralized trade router'.",
    "LineLock – Transitioned from 'time-lock vault' to 'token vesting service'.",
    "FlockDAO – Transitioned from 'community DAO aggregator' to 'interoperable governance hub'.",
    "VybeStream – Transitioned from 'music streaming aggregator' to 'social audio NFT platform'.",
    "MeshSwap – Transitioned from 'single-chain DEX' to 'multi-chain liquidity aggregator'.",
    "FireBridge – Transitioned from 'ETH-BTC bridge' to 'generic EVM bridging layer'.",
    "DataRoo – Transitioned from 'analytics aggregator' to 'on-chain machine learning hub'.",
    "RareWatch – Transitioned from 'NFT rarity tool' to 'AI-driven NFT insights'.",
    "ChainFarm – Transitioned from 'yield farming aggregator' to 'metamarket yield orchestration'.",
    "ArtiFlex – Transitioned from 'digital art marketplace' to 'curated NFT aggregator'.",
    "LendDoor – Transitioned from 'crowdlending platform' to 'tokenized credit lines'.",
    "BoardMeld – Transitioned from 'governance board aggregator' to 'ZK-based voting layer'.",
    "PoolLine – Transitioned from 'liquidity pool aggregator' to 'DeFi multi-chain suite'.",
    "PollyMerkle – Transitioned from 'merkle tree aggregator' to 'on-chain proof aggregator'.",
    "SolarSwipe – Transitioned from 'solar energy tokens' to 'utility-based NFT marketplace'.",
    "CubistX – Transitioned from 'crypto dev toolkit' to 'modular app chain aggregator'.",
    "ScaleNode – Transitioned from 'validator aggregator' to 'automated staking manager'.",
    "MetaCart – Transitioned from 'tokenized e-commerce' to 'NFT-based store aggregator'.",
    "FluxLedger – Transitioned from 'micro-payments aggregator' to 'streaming finance engine'.",
    "GammaPort – Transitioned from 'DeFi portfolio tracker' to 'NFT & DeFi aggregator'.",
    "VaultSquare – Transitioned from 'ETH staking pool' to 'liquid cross-chain staking'.",
    "NodeFunnel – Transitioned from 'infrastructure aggregator' to 'multi-chain node marketplace'.",
    "KeySmith – Transitioned from 'crypto key management' to 'multichain identity layer'.",
    "WispSwap – Transitioned from 'arbitrage aggregator' to 'auto-optimizing DEX aggregator'.",
    "GraphBolt – Transitioned from 'data indexing aggregator' to 'modular subgraph solutions'.",
    "KaleidoGenius – Transitioned from 'NFT gallery' to 'AI-based NFT creation suite'.",
    "ChainQuarry – Transitioned from 'miner aggregator' to 'modular PoS & PoW aggregator'.",
    "LockHive – Transitioned from 'locked staking aggregator' to 'on-chain escrow solutions'.",
    "MeterGen – Transitioned from 'metered gas aggregator' to 'dynamic gas fee solutions'.",
    "PrimeFlow – Transitioned from 'MEV aggregator' to 'anti-MEV rollup solution'.",
    "ProtoBloom – Transitioned from 'proto-danksharding aggregator' to 'modular data shards'.",
    "SiloStash – Transitioned from 'yield aggregator' to 'cross-layer yield aggregator'.",
    "VisaRaft – Transitioned from 'crypto payments aggregator' to 'web3 subscription platform'.",
    "CeloSolve – Transitioned from 'mobile DeFi aggregator' to 'layer-2 bridging suite'.",
    "AlphaTrunk – Transitioned from 'NFT collection aggregator' to 'fractional NFT marketplace'.",
    "SkyTrack – Transitioned from 'token airdrop aggregator' to 'airdrop analytics tool'.",
    "PsiGauge – Transitioned from 'risk analysis aggregator' to 'on-chain risk scoring system'.",
    "RhinoDock – Transitioned from 'crypto exchange aggregator' to 'unified trading terminal'.",
    "OrbitMint – Transitioned from 'layer-2 aggregator' to 'celestia-based chain aggregator'.",
    "NodeOrb – Transitioned from 'node hosting aggregator' to 'cross-chain node infra suite'.",
    "BeamByte – Transitioned from 'decentralized streaming aggregator' to 'web3 video DAO'.",
    "DreamFoundry – Transitioned from 'game asset aggregator' to 'blockchain gaming marketplace'.",
    "CrossLink – Transitioned from 'bridge aggregator' to 'virtual chain bridging hub'.",
    "VaultArk – Transitioned from 'NFT vault aggregator' to 'NFT fractionalization platform'.",
    "MintStorm – Transitioned from 'NFT launch aggregator' to 'multi-chain minting tool'.",
    "SpinGear – Transitioned from 'DEX aggregator' to 'automated trading strategies suite'.",
    "RollWrap – Transitioned from 'rollup aggregator' to 'layer-2 chain aggregator'.",
    "MaxLend – Transitioned from 'lending aggregator' to 'NFT-based collateral manager'.",
    "StarDock – Transitioned from 'multichain staking aggregator' to 'cosmos-based hub extension'.",
    "PixelFlow – Transitioned from 'NFT creation aggregator' to 'AI generative art engine'.",
    "CoinCreek – Transitioned from 'crypto faucet aggregator' to 'on-chain reward system'.",
    "LensGate – Transitioned from 'social media aggregator' to 'Lens Protocol-based media suite'.",
    "ShroomMine – Transitioned from 'fungi-inspired NFT aggregator' to 'gamified spore token model'.",
    "MinerX – Transitioned from 'bitcoin mining aggregator' to 'tokenized hashpower market'.",
    "LoomZoom – Transitioned from 'Loom sidechain aggregator' to 'metaverse expansion solution'.",
    "EverLink – Transitioned from 'chain interoperability aggregator' to 'cross-rollup synergy'.",
    "StackShift – Transitioned from 'development aggregator' to 'web3 dev environment suite'.",
    "WarpFlux – Transitioned from 'transaction aggregator' to 'MEV-protected routing'.",
    "ArkHaven – Transitioned from 'insurance aggregator' to 'tokenized coverage pools'.",
    "QuestSpan – Transitioned from 'task aggregator' to 'web3 freelance marketplace'.",
    "FloodGate – Transitioned from 'block producer aggregator' to 'dynamic blockspace manager'.",
    "ChainCub – Transitioned from 'youth education aggregator' to 'NFT-based learning badges'.",
    "ZapTorch – Transitioned from 'token burning aggregator' to 'deflationary dApp aggregator'.",
    "RoseQuilt – Transitioned from 'NFT tapestry aggregator' to 'on-chain generative patterns'.",
    "MatrixMate – Transitioned from 'frontrunning aggregator' to 'anti-sandwich protocol layer'.",
    "ParallelBridge – Transitioned from 'cross-parachain aggregator' to 'substrate bridging suite'.",
    "TideFlow – Transitioned from 'liquidity aggregator' to 'concentrated liquidity manager'.",
    "BlurOrbit – Transitioned from 'NFT aggregator' to 'cross-market NFT aggregator'.",
    "NodeMap – Transitioned from 'decentralized location aggregator' to 'trusted geolocation layer'.",
    "ProtoFocus – Transitioned from 'DeFi aggregator' to 'MEV-proof aggregator layer'.",
    "HedgePulse – Transitioned from 'hedging aggregator' to 'options & futures aggregator'.",
    "MirrorRoute – Transitioned from 'synthetic aggregator' to 'multi-asset derivative aggregator'.",
    "StrataForge – Transitioned from 'layer aggregator' to 'multi-domain bridging chain'.",
    "FrostedX – Transitioned from 'futures aggregator' to 'cross-chain perps platform'.",
    "QuietLock – Transitioned from 'privacy aggregator' to 'zkRollup-based private transactions'.",
    "GaugeSpan – Transitioned from 'governance aggregator' to 'voting power aggregator'.",
    "Arkeseed – Transitioned from 'crowdfunding aggregator' to 'equity token platform'.",
    "DeltaPull – Transitioned from 'price feed aggregator' to 'oracle bridging framework'.",
    "PranaFlow – Transitioned from 'carbon credit aggregator' to 'NFT-based carbon offsetting'.",
    "LinkBound – Transitioned from 'cross-chain aggregator' to 'relayer-based L2 aggregator'.",
    "DawnHatch – Transitioned from 'incubation aggregator' to 'web3 project accelerators'.",
    "SparkBatch – Transitioned from 'batch transaction aggregator' to 'gas optimization suite'.",
    "AutoSpread – Transitioned from 'arbitrage aggregator' to 'auto route aggregator'.",
    "JetFlux – Transitioned from 'multichain aggregator' to 'gasless bridging aggregator'.",
    "MeldDeck – Transitioned from 'DeFi aggregator' to 'token bridging aggregator'.",
    "LotusRift – Transitioned from 'bridge aggregator' to 'NFT bridging aggregator'.",
    "FloraStake – Transitioned from 'NFT staking aggregator' to 'web3 collectible staking'.",
    "GridWatt – Transitioned from 'energy aggregator' to 'tokenized renewable energy platform'.",
    "BetaSeed – Transitioned from 'startup token aggregator' to 'token-based VC aggregator'.",
    "ScriptHive – Transitioned from 'smart contract aggregator' to 'no-code contract generation'.",
    "ChromaLink – Transitioned from 'color-based NFT aggregator' to 'fractional pixel ownership'.",
    "ParcelWave – Transitioned from 'logistics aggregator' to 'NFT-based shipping tokens'.",
    "FlowPad – Transitioned from 'IDO aggregator' to 'multi-chain launchpad suite'.",
    "ApexNodes – Transitioned from 'node aggregator' to 'PoS aggregator manager'.",
    "SenseRune – Transitioned from 'narrative aggregator' to 'interactive storyline NFTs'.",
    "MuralVerse – Transitioned from 'digital mural aggregator' to 'AR NFT experiences'.",
    "BlockTap – Transitioned from 'on-chain scoreboard' to 'web3 scoreboard aggregator'.",
    "CoinBrain – Transitioned from 'AI aggregator' to 'token intelligence platform'.",
    "MintMate – Transitioned from 'NFT aggregator' to 'airdrop aggregator suite'.",
    "VentureMesh – Transitioned from 'web3 funding aggregator' to 'DAO-based investment platform'.",
    "PetriVault – Transitioned from 'liquidity aggregator' to 'cross-protocol vault aggregator'.",
    "SwanDex – Transitioned from 'lightweight DEX aggregator' to 'mobile-first DEX aggregator'.",
    "CtrlBoard – Transitioned from 'governance aggregator' to 'multi-chain DAO dashboard'.",
    "NetWeave – Transitioned from 'privacy aggregator' to 'mixnet integration aggregator'.",
    "CarveIt – Transitioned from 'metaverse aggregator' to 'community-based NFT aggregator'.",
    "MagniFlow – Transitioned from 'ETL aggregator' to 'big data on-chain aggregator'.",
    "ArcLink – Transitioned from 'arbitrary message aggregator' to 'cross-layer messaging solution'.",
    "MetaSpree – Transitioned from 'virtual marketplace aggregator' to 'web3 shopping aggregator'.",
    "ShaftDex – Transitioned from 'miner aggregator' to 'miner reward optimization suite'.",
    "GemShine – Transitioned from 'gemstone NFT aggregator' to 'real-world asset token platform'.",
    "LiftSpan – Transitioned from 'crowdsourcing aggregator' to 'token-based gig platform'.",
    "WaveTide – Transitioned from 'music aggregator' to 'token-based streaming aggregator'.",
    "LoomShift – Transitioned from 'layer aggregator' to 'L2 bridging aggregator'.",
    "PixelSquad – Transitioned from 'NFT aggregator' to 'customizable NFT avatars platform'.",
    "FiberLink – Transitioned from 'fiber network aggregator' to 'internet access on-chain model'.",
    "CoreProxy – Transitioned from 'sidechain aggregator' to 'modular chain orchestration'.",
    "NectarSwap – Transitioned from 'swapping aggregator' to 'ZK aggregator for token swaps'.",
    "DeltaLens – Transitioned from 'trading aggregator' to 'analytics-based DEX aggregator'.",
    "EchoStash – Transitioned from 'collateral aggregator' to 'multi-asset collateral pooling'.",
    "OrionLock – Transitioned from 'custody aggregator' to 'token vault aggregator'.",
    "RadialFlow – Transitioned from 'liquidity aggregator' to 'hub-and-spoke bridging model'.",
    "TesserVault – Transitioned from 'NFT aggregator' to 'time-based NFT vaulting'.",
    "NovaArc – Transitioned from 'launch aggregator' to 'multi-chain IDO aggregator'.",
    "RangeStake – Transitioned from 'variable APY aggregator' to 'risk-adjusted staking aggregator'.",
    "CloverLane – Transitioned from 'DeFi aggregator' to 'rewards aggregator platform'.",
    "MetaVille – Transitioned from 'metaverse aggregator' to 'interoperable metaverse gateway'.",
    "IslandCast – Transitioned from 'micro streaming aggregator' to 'pay-per-second streaming'.",
    "BlokTurf – Transitioned from 'land registry aggregator' to 'tokenized real estate aggregator'.",
    "CarbonSpan – Transitioned from 'carbon aggregator' to 'multi-chain carbon bridging'.",
    "PolyDock – Transitioned from 'polkadot aggregator' to 'cross-parachain aggregator'.",
    "KeyVerse – Transitioned from 'credential aggregator' to 'soulbound tokens manager'.",
    "DustBin – Transitioned from 'trash-to-treasure aggregator' to 'recycle-based NFT system'.",
    "SpearMint – Transitioned from 'NFT aggregator' to 'creator launch aggregator'.",
    "DriftPool – Transitioned from 'NFT liquidity aggregator' to 'AMM for NFT swaps'.",
    "SkyFang – Transitioned from 'airdrop aggregator' to 'advanced airdrop analytics suite'.",
    "MatrixBond – Transitioned from 'token aggregator' to 'DeFi bond aggregator'.",
    "TempoPay – Transitioned from 'micro-payment aggregator' to 'recurring subscription aggregator'.",
    "RhythMatic – Transitioned from 'music aggregator' to 'DAO-based music rights aggregator'.",
    "OrbitRex – Transitioned from 'space-tech aggregator' to 'satellite data tokenization'.",
    "FieldFunder – Transitioned from 'agriculture aggregator' to 'crowdfunded farm tokens'.",
    "MystiChain – Transitioned from 'mystery box aggregator' to 'NFT loot aggregator'.",
    "VeriBoard – Transitioned from 'verification aggregator' to 'on-chain credential solutions'.",
    "NodeStack – Transitioned from 'blockchain infra aggregator' to 'multichain cloud aggregator'.",
    "TiltShift – Transitioned from 'NFT aggregator' to 'photo-centric NFT marketplace'.",
    "VitruMint – Transitioned from 'dynamic NFT aggregator' to 'real-time NFT updates layer'.",
    "TribalFlow – Transitioned from 'community aggregator' to 'token-based tribe governance'.",
    "ApexNook – Transitioned from 'metaverse aggregator' to 'VR-based NFT aggregator'.",
    "PanoraMint – Transitioned from 'photography NFT aggregator' to 'image rights marketplace'.",
    "WispWeave – Transitioned from 'zero-knowledge aggregator' to 'zkRollup aggregator suite'.",
    "CrowdLoom – Transitioned from 'crowdfunding aggregator' to 'token-based project fundraising'.",
    "EonStake – Transitioned from 'validator aggregator' to 'cross-chain staking aggregator'.",
    "RevoQuest – Transitioned from 'rewards aggregator' to 'mission-based NFT achievements'.",
    "GateShard – Transitioned from 'shard aggregator' to 'multi-shard bridging network'.",
    "GreenFi – Transitioned from 'eco aggregator' to 'sustainability token aggregator'.",
    "SentryDeal – Transitioned from 'escrow aggregator' to 'multi-chain escrow solution'.",
    "DriftAxle – Transitioned from 'auto aggregator' to 'car NFT marketplace & aggregator'.",
    "MemeRift – Transitioned from 'meme token aggregator' to 'crowdsourced memecoin hub'.",
    "PulseForge – Transitioned from 'hash aggregator' to 'tokenizing hashing power'.",
    "AriaNote – Transitioned from 'music aggregator' to 'crowdsourced song rights tokenization'.",
    "DarkLoom – Transitioned from 'privacy aggregator' to 'secret contract aggregator'.",
    "EquipMint – Transitioned from 'gaming gear aggregator' to 'web3 in-game asset aggregator'.",
    "PlantDAO – Transitioned from 'plant-based aggregator' to 'tokenized sustainable farming'.",
    "FluxDoor – Transitioned from 'storage aggregator' to 'p2p storage solutions aggregator'.",
    "TallyBond – Transitioned from 'bond aggregator' to 'liquid bond marketplace'.",
    "FractalLock – Transitioned from 'fractal NFT aggregator' to 'generative fractal aggregator'.",
    "CloverDock – Transitioned from 'e-commerce aggregator' to 'web3 brand marketplace'.",
    "RippleTune – Transitioned from 'music aggregator' to 'royalty-splitting NFT platform'.",
    "JetVortex – Transitioned from 'multichain aggregator' to 'token bridging aggregator'.",
    "ArcBeacon – Transitioned from 'oracle aggregator' to 'data feed aggregator for NFTs'.",
    "BasinFlow – Transitioned from 'liquidity aggregator' to 'layer-2 pool aggregator'.",
    "CosmicStage – Transitioned from 'metaverse events aggregator' to 'NFT-based ticket aggregator'.",
    "SentryNode – Transitioned from 'node aggregator' to 'automated validator manager'.",
    "PlumeChain – Transitioned from 'messaging aggregator' to 'lightweight cross-chain comms'.",
    "IngotMint – Transitioned from 'gold token aggregator' to 'commodity-based token aggregator'.",
    "QuantumWeave – Transitioned from 'quantum-safe aggregator' to 'post-quantum key manager'.",
    "LinkPivot – Transitioned from 'API aggregator' to 'blockchain integration aggregator'.",
    "RadiaLink – Transitioned from 'L2 aggregator' to 'rollup aggregator for large-scale dApps'.",

    "Notion - Transitioned from a note-taking tool to an all-in-one productivity platform.",
    "Clubhouse - Initially launched as a podcasting app, pivoted to become a live audio social platform.",
    "Peloton - Expanded its narrative from fitness equipment to a content-driven fitness platform.",
    "Calm - Pivoted from a mindfulness app to a comprehensive mental wellness brand.",
    "Robinhood - Initially a stock-trading app, expanded into crypto trading and financial education.",
    "Figma - Shifted from a design tool to a full-fledged collaboration platform for teams.",
    "DoorDash - Expanded from food delivery to focus on last-mile logistics solutions.",
    "AirUp - Pivoted from a health-focused startup to creating scent-based hydration solutions.",
    "Canva - Transitioned from a simple design tool to an end-to-end visual communication suite.",
    "Hopin - Started as a virtual events platform, expanded into a hybrid events solution.",
    "Rivian - Pivoted from building electric sports cars to electric adventure vehicles.",
    "Oura Ring - Expanded from sleep tracking to a comprehensive health and wellness wearable.",
    "Zoom - Moved from enterprise communication to becoming a household video conferencing tool during the pandemic.",
    "Superhuman - Originally an email productivity tool, pivoted to position itself as a premium email experience.",
    "BetterHelp - Transitioned from an online therapy service to a holistic mental health platform.",
    "Cameo - Pivoted from celebrity shoutouts to offering personalized experiences and content.",
    "Loom - Shifted from a screen recording tool to a remote work productivity enabler.",
    "Thrasio - Initially an Amazon product aggregator, pivoted to focus on building consumer brands.",
    "Epic Games - Expanded from game development to creating the Unreal Engine as a core offering.",
    "Duolingo - Transitioned from a language-learning app to a broader education platform with math and literacy.",
    "ByteDance (TikTok) - Initially focused on short lip-sync videos, pivoted to include diverse content.",
    "Pinterest - Added e-commerce tools to become a shopping-enabled visual discovery platform.",
    "Etsy - Shifted focus from handmade goods to a broader marketplace for unique items.",
    "Squarespace - Expanded from website building to include marketing and e-commerce solutions.",
    "Hims & Hers - Pivoted from a men's health startup to a comprehensive telehealth brand.",
    "Lemonade - Evolved from a renter's insurance company to a full-stack insurance platform.",
    "Patreon - Shifted from creator funding to offering full-fledged membership management tools.",
    "LinkedIn - Transitioned from professional networking to emphasize learning and job opportunities.",
    "Tesla - Evolved from electric vehicles to sustainable energy products and services.",
    "Blue Apron - Pivoted from meal kits to prepared meal delivery during the pandemic.",
    "Uber - Expanded from ride-sharing to delivery (Uber Eats) and freight logistics.",
    "Lyft - Shifted from ride-sharing to focus on transportation as a service (TaaS).",
    "Reddit - Transitioned from content aggregation to monetized community engagement.",
    "WeWork - Moved from coworking spaces to offering hybrid work solutions.",
    "Instacart - Pivoted from grocery delivery to enterprise solutions for retailers.",
    "GoPuff - Expanded from convenience store delivery to include prepared foods.",
    "Match Group - Evolved from dating apps to creating deeper social connection tools.",
    "Bumble - Transitioned from a dating app to a platform for professional networking and friendships.",
    "Spotify - Added podcasts and exclusive audio content to its music streaming service.",
    "Roku - Pivoted from hardware sales to building a streaming content ecosystem.",
    "Peloton - Added gamification and social features to its fitness platform.",
    "Hopper - Expanded from flight booking to offering travel financial products.",
    "Udemy - Transitioned from individual courses to enterprise learning solutions.",
    "Coursera - Shifted focus from free courses to degree programs and certificates.",
    "Asana - Evolved from project management software to a work orchestration platform.",
    "Slack - Moved beyond communication to emphasize workflows and integrations.",
    "Headspace - Transitioned from a meditation app to a holistic mental health provider.",
    "Eero - Pivoted from mesh Wi-Fi hardware to building smart home ecosystems.",
    "Ring - Expanded from video doorbells to comprehensive home security solutions.",
    "Peloton - Focused on fitness-as-a-service with new subscription models.",
    "Squarespace - Added email marketing and e-commerce to its website builder.",
    "Cameo - Focused on corporate and group engagement solutions.",
    "Airbnb - Transitioned from short-term stays to curated travel experiences.",
    "Oura Ring - Added workout and stress tracking to its health focus.",
    "Glossier - Evolved into a lifestyle brand from direct-to-consumer beauty.",
    "Thrasio - Focused on brand development over simple aggregation.",
    "Docusign - Moved from e-signatures to broader contract lifecycle management.",
    "HubSpot - Expanded from CRM to an all-in-one marketing and sales platform.",
    "Stripe - Added global commerce tools beyond payment processing.",
    "Square - Rebranded as Block and expanded into digital wallets and banking.",
    "Pinterest - Introduced AR and AI for shopping integration.",
    "Eventbrite - Focused on hybrid event solutions.",
    "Robinhood - Added retirement accounts and crypto staking.",
    "Nextdoor - Evolved into a local commerce and community hub.",
    "Etsy - Shifted focus to sustainable and vintage products.",
    "Hims & Hers - Added subscription wellness services.",
    "Dropbox - Expanded into document and workflow management.",
    "Clio - Transitioned from legal practice software to a full legal operating system.",
    "PagerDuty - Added predictive analytics to its incident response system.",
    "Canva - Launched team collaboration tools.",
    "Slack - Added video messaging for asynchronous communication.",
    "Roku - Focused on creating original content.",
    "Zoom - Expanded into hybrid work collaboration tools.",
    "DoorDash - Added DashMart convenience stores to its ecosystem.",
    "Stitch Fix - Moved to personalized e-commerce.",
    "Lime - Expanded into multi-modal micromobility solutions.",
    "Bird - Focused on partnerships with cities for shared mobility.",
    "Strava - Transitioned to offering challenges and coaching features.",
    "Patreon - Added digital storefronts for creators.",
    "Hinge - Focused on long-term relationships rather than casual dating.",
    "Duolingo - Added gamified content for kids and other subjects.",
    "Fiverr - Moved from gig work to managed service marketplaces.",
    "Upwork - Focused on enterprise solutions for hiring remote talent.",
    "Gong - Expanded from sales analytics to broader revenue intelligence.",
    "Plaid - Added insights and tools for fintech app developers.",
    "Notion - Launched team databases and collaboration tools.",
    "Calendly - Evolved into an all-in-one scheduling automation platform.",
];

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Define the path to additionalStartups.json
const ADDITIONAL_STARTUPS_PATH = path.resolve(
    __dirname,
    "../src/data/additionalStartups.json"
);
const USED_STARTUPS_PATH = path.resolve(
    __dirname,
    "../src/data/usedStartups.json"
);

console.log("Resolved Path:", ADDITIONAL_STARTUPS_PATH);
console.log("Resolved Path:", USED_STARTUPS_PATH);

// Function to load startups (additional or used)
async function loadStartups(filePath: string): Promise<string[]> {
    try {
        const data = await fs.readFile(filePath, "utf8");
        return JSON.parse(data);
    } catch (error) {
        // If file doesn't exist or is invalid, return an empty array
        console.log(error);
        return [];
    }
}

export async function saveStartup(startup: string, filePath: string) {
    const startupName = extractStartupName(startup);
    console.log("makinggggg7");
    console.log(startupName)
    console.log("startup",startup)
    if (startupName) {
        const startups = await loadStartups(filePath);

        // Check if the startup name is already included in any of the startup strings
        const isStartupExist = startups.some((existingStartup) => {
            const existingStartupName = extractStartupName(existingStartup);
            return existingStartupName === startupName;
        });

        // Only add if the startup name is not already in the list
        if (!isStartupExist) {
            startups.push(startup);

            await fs.writeFile(filePath, JSON.stringify(startups, null, 2));
        }
    } else {
        console.error("Invalid startup input: No startup name found");
    }
}

// Functions for loading additional and used startups
export async function loadAdditionalStartups() {
    return await loadStartups(ADDITIONAL_STARTUPS_PATH);
}

export async function loadUsedStartups() {
    return await loadStartups(USED_STARTUPS_PATH);
}

// Functions for saving additional and used startups
export async function saveAdditionalStartup(startup: string) {
    await saveStartup(startup, ADDITIONAL_STARTUPS_PATH);
}

export async function saveUsedStartup(startup: string) {
    await saveStartup(startup, USED_STARTUPS_PATH);
}

export function extractStartupName(inputString: string): string | null {
    /**
     * Extracts the startup name from the input string.
     *
     * @param inputString - The string containing the startup name.
     * @returns The extracted startup name or null if not found.
     */
    const match = inputString.match(/username:\s*(@[\w\d]+)/);


    if (match) {
        return match[1].trim(); // Return the captured group (startup name)
    }
    return null;
}
